### ISSUE TITLE
Write winter... in winter?!?

### ISSUE THREAD

**Issue by talwat** [dustin4242/winter#2]
Hey dustin!

I've noticed that you're working on winter again, which is pretty cool.

I wanted to suggest something which could be interesting, in that when you start writing a standard library, try and do something like rust where you have a standard library which is written in the language itself. So you add the bare-bones functions to read/write to memory and such in rust (maybe under a separate library like `core` or whatever) and then you are able to use those to make print functions and so on so fourth. Just a suggestion, although, I think it'll get horrifically ugly if you have to define every single function in the standard library in the core of the programming language.

**Comment by dustin4242** [comment]
I've been holding off on writing a comment for this because I can't really say much else other than this seems like an excellent idea. I don't know exactly how winter is going to read/write to memory yet but I'll get there eventually. Also on the standard library thing: I do agree it may get difficult to write the standard library with EVERY function I want to use such as `print` however because it is defined in such a way it makes the language easily expandable by anyone wanting to use it, which is my intention with that feature.

**Comment by talwat** [comment]
Yeah, I noticed you defined print with rust in a separate file, and I think that's the same place you could implement core functionality. If you wanted to make a print function in winter for example, you would need to simply implement a way to write to files/devices, and if you wrote to /dev/stdout (I believe it is) then you have your print. My point is that you implement core functionality and do the rest in winter, which would lead to something way easier to maintain. You could also figure out something where you have winter bindings for rust libraries, sort of like python and C.

**Comment by dustin4242** [comment]
Understood 👍

**Comment by dustin4242** [comment]
Implemented file-writes last night and got some output examples going using that to write to /dev/stdout

**Comment by talwat** [comment]
Awesome!
